theme = "base16_default"
[editor]
line-number = "relative"
auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true
git-ignore = true

[editor.whitespace.render]
newline = "all"

[editor.soft-wrap]
enable = true

[keys.insert]
"esc" = ["normal_mode", ":w"]

[keys.normal]
"esc" = [":w"]
