theme = "dark_plus"

[editor]
line-number = "relative"
auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.whitespace.render]
newline = "all"

[editor.soft-wrap]
enable = true

[keys.insert]
"esc" = ["normal_mode", ":w"]
