bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind a command-prompt -p "join pane from:"  "join-pane -s '%%'"

set -g default-command /usr/bin/fish
set -g default-shell /usr/bin/fish

set-option -g history-limit 100000
set-option -g renumber-windows on
