theme = "gruvbox_light"

[editor]
line-number = "relative"
auto-save = true
auto-pairs = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true
git-ignore = true

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[keys.insert]
"esc" = ["normal_mode", ":w"]

[keys.normal]
"esc" = [":w"]

[keys.normal.space]
n = ":insert-output date +'%%H:%%M'"
W = ":reflow"
l = "@ms[a()<esc>;<space>P"
